# Generated by Django 4.2.20 on 2025-03-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("proctoring", "0003_customuser_delete_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="CustomUser", new_name="User",),
    ]
