# Generated by Django 4.2.20 on 2025-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctoring", "0004_rename_customuser_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="exam", name="created_by",),
        migrations.RemoveField(model_name="exam", name="duration",),
        migrations.AlterField(
            model_name="exam", name="password", field=models.CharField(max_length=20),
        ),
    ]
